
PROJECT := parsi
TYPE := Executable

HEADERS := parsiexception.hpp

SOURCES := main_parsi.cpp

LIBS := -lCore \
	-lStreamIO \
	-lType \
	-lConfiguration \
	-lEncoding \
	-lCompression \
	-lCryptography \
	-lThreading \
	-lLibrary \
	-lMVCCS \
	-lCompiler \
	-lpthread

include ../Makefile.global
