
PROJECT := ziguratip
TYPE := Executable

HEADERS := 

SOURCES := shared.cpp \
	loadmemory.cpp \
	loadlibrary.cpp \
	loadcompiler.cpp \
	loadsecurity.cpp \
	loadzigurat.cpp \
	loadzeytun.cpp \
	main_ziguratip.cpp

LIBS :=  -lStreamIO \
	-lType \
	-lCore \
	-lLibrary \
	-lCompression \
	-lEncoding \
	-lCryptography \
	-lConfiguration \
	-lThreading \
	-lSocketIO \
	-lCompiler \
	-lMVCCS \
	-lMVCCS2 \
	-lConnector \
	-lHTTP \
	-lpthread

include ../Makefile.global
