
PROJECT := parsic
TYPE := Executable

HEADERS :=

SOURCES := main_parsic.cpp

LIBS := -lConnector \
	-lStreamIO \
	-lType \
	-lCore \
	-lLibrary \
	-lConfiguration \
	-lEncoding \
	-lCompression \
	-lCryptography \
	-lThreading \
	-lSocketIO \
	-lMVCCS \
	-lz \
	-lpthread

include ../Makefile.global
