
PROJECT := Test
TYPE := Executable

HEADERS :=

SOURCES := main_test.cpp \
	test_core.cpp \
	test_streamio.cpp \
	test_socketio.cpp \
	test_tls.cpp \
	test_threading.cpp \
	test_cryptography.cpp \
	test_encoding.cpp \
	test_configuration.cpp \
	test_type.cpp \
	test_mvccs.cpp \
	test_btree.cpp \
	test_modelpool.cpp \
	test_misc.cpp \
	test_acid.cpp \
	test_isolation.cpp \
	test_concurrency.cpp \
	test_zeytun.cpp \
	test_grammar.cpp \
	test_permissions.cpp

LIBS := -lStreamIO \
	-lType \
	-lCore \
	-lLibrary \
	-lCompression \
	-lEncoding \
	-lCryptography \
	-lConfiguration \
	-lThreading \
	-lSocketIO \
	-lCompiler \
	-lMVCCS \
	-lConnector \
	-lHTTP \
	-lz \
	-lpthread

include ../Makefile.global
