#!/bin/sh
# Build the neural-network object from Cicili's emitted fragment, serve it, and
# ask it for predictions over HTTP.
#
#   Test/run-ai-e2e.sh                 against the torch stub -- always runs
#   TORCH_ROOT=/opt/torch/torch \
#     Test/run-ai-e2e.sh               against the real libtorch
#   CICILI_ROOT=../cicili \
#     Test/run-ai-e2e.sh               also re-emit the fragment and diff it
#
# WHAT IT COVERS. The whole path in one go: C++ generated by Cicili from a
# (network …) description, spliced into a Parsi CLASS through BEGIN HPP and
# BEGIN CPP, compiled standalone into home/ld/lib_DEMO::CLASSIFIER_.so, loaded
# by the server, and reached by a page over HTTP. Nothing else in either
# repository's suite touches more than a piece of that.
#
# WHAT IT DOES NOT COVER. Whether the model is any good. The stub's Linear is
# not trained and neither is the real one here -- net_load is given an empty
# path on purpose. No assertion below reads an accuracy, and none should be
# added: this is a test of the plumbing, and a plumbing test that starts
# claiming things about a model is how a suite stops being trusted.

set -e

HERE=$(cd "$(dirname "$0")" && pwd)
TRUNK=$(cd "$HERE/.." && pwd)
HOME_DIR="$TRUNK/home"
AI="$HERE/ai"

pass=0
fail=0

check() {
  # check NAME ACTUAL EXPECTED -- an empty ACTUAL is never a pass, for the same
  # reason as check_ne: nothing compares equal to nothing a little too easily.
  if [ -z "$2" ]; then
    echo "FAIL $1: got nothing, want '$3'"
    fail=$((fail + 1))
  elif [ "$2" = "$3" ]; then
    echo "ok   $1"
    pass=$((pass + 1))
  else
    echo "FAIL $1: got '$2' want '$3'"
    fail=$((fail + 1))
  fi
}

check_ne() {
  # check_ne NAME A B  -- the two must DIFFER, and neither may be empty.
  #
  # THE EMPTY CASE IS THE ONE THAT MATTERS. When the page answers nothing --
  # a server not up yet, an object that would not load -- every field parses
  # as the empty string, and "" differs from nothing and equals everything.
  # Without this guard a total failure to reach the model reads as agreement.
  if [ -z "$2" ] || [ -z "$3" ]; then
    echo "FAIL $1: one side was empty, so there was nothing to compare"
    fail=$((fail + 1))
  elif [ "$2" != "$3" ]; then
    echo "ok   $1"
    pass=$((pass + 1))
  else
    echo "FAIL $1: both were '$2', expected them to differ"
    fail=$((fail + 1))
  fi
}

if [ ! -x "$HOME_DIR/bin/ziguratip" ]; then
  echo "build first: make -C $TRUNK" >&2
  exit 1
fi

# --- the fragment ----------------------------------------------------------
#
# Test/ai/classifier.{hpp,cpp} are committed, so this runs with no Cicili
# checkout at all. With one, they are re-emitted and diffed -- which is what
# catches the generator drifting away from the copy committed here. A drift is
# a failure, not a silent overwrite: the point is to be told.

if [ -n "$CICILI_ROOT" ]; then
  CICILI_ROOT=$(cd "$CICILI_ROOT" && pwd)
  echo "re-emitting the fragment from $CICILI_ROOT"
  ( cd "$CICILI_ROOT" && sbcl --script cicili.lisp ./example/mnist-fragment.cicili >/tmp/ai-emit.log 2>&1 ) \
    || { echo "FAIL cicili could not emit the fragment; see /tmp/ai-emit.log"; exit 1; }
  for f in classifier.hpp classifier.cpp; do
    if diff -q "$CICILI_ROOT/example/$f" "$AI/$f" >/dev/null 2>&1; then
      check "$f matches what cicili emits" "same" "same"
    else
      check "$f matches what cicili emits" "differs" "same"
      diff -u "$AI/$f" "$CICILI_ROOT/example/$f" | head -30
    fi
  done
else
  echo "note: CICILI_ROOT unset, using the committed fragment as-is"
fi

# --- the torch header ------------------------------------------------------

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# STAGE INTO home/tmp, NOT JUST home/ld, and clear what was there first.
#
# The generated _DEMO::CLASSIFIER_.cpp is written into home/tmp and compiled
# there, and `#include "torch_stub.hpp"' is a quoted include -- so the
# compiler looks in home/tmp before it looks anywhere on -I. A stale copy left
# in home/tmp from an earlier run is therefore the one that gets compiled, and
# nothing says so: the build succeeds, the page answers, and every assertion
# passes against a header nobody edited.
#
# This is not hypothetical. It is what happened while this script was being
# written -- a deliberately broken stub was staged, the suite went green, and
# the reason was a copy in home/tmp from an earlier compile. Clearing both
# directories is what makes an edit to Test/ai/ actually reach the object.
rm -f "$HOME_DIR/tmp/torch_stub.hpp" "$HOME_DIR/tmp/classifier.hpp" "$HOME_DIR/tmp/classifier.cpp" \
      "$HOME_DIR/ld/torch_stub.hpp"  "$HOME_DIR/ld/classifier.hpp"  "$HOME_DIR/ld/classifier.cpp" \
      "$HOME_DIR/ld/lib_DEMO::CLASSIFIER_.so" "$HOME_DIR/obj/_DEMO::CLASSIFIER_.o" \
      "$HOME_DIR/ld/lib_PREDICT_.so"          "$HOME_DIR/obj/_PREDICT_.o"

cp "$AI/classifier.hpp" "$AI/classifier.cpp" "$HOME_DIR/ld/"
cp "$AI/classifier.hpp" "$AI/classifier.cpp" "$HOME_DIR/tmp/"

if [ -n "$TORCH_ROOT" ]; then
  if [ ! -f "$TORCH_ROOT/include/torch/torch.h" ] && [ ! -f "$TORCH_ROOT/include/torch/csrc/api/include/torch/torch.h" ]; then
    echo "FAIL TORCH_ROOT=$TORCH_ROOT has no include/torch/torch.h" >&2
    exit 1
  fi
  echo "tier B: against the real libtorch at $TORCH_ROOT"
  sed -e 's|#include "torch_stub.hpp"|#include <torch/torch.h>|' \
      -e "s|INCLUDE '<memory>';|INCLUDE '<memory>';\n\tLINK '-L$TORCH_ROOT/lib';\n\tLINK '-ltorch';\n\tLINK '-ltorch_cpu';\n\tLINK '-lc10';|" \
      "$AI/classifier.parsi" > "$WORK/classifier.parsi"
  CPPFLAGS="-I$TORCH_ROOT/include -I$TORCH_ROOT/include/torch/csrc/api/include"
  export CPPFLAGS
else
  echo "tier A: against Test/ai/torch_stub.hpp (set TORCH_ROOT for the real library)"
  cp "$AI/torch_stub.hpp" "$HOME_DIR/ld/"
  cp "$AI/torch_stub.hpp" "$HOME_DIR/tmp/"
  cp "$AI/classifier.parsi" "$WORK/classifier.parsi"
fi

export ZIGURATIP_HOME="$HOME_DIR"
export DYLD_LIBRARY_PATH="$HOME_DIR/lib:$DYLD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$HOME_DIR/lib:$LD_LIBRARY_PATH"

echo "compiling the object"
"$HOME_DIR/bin/parsi" "$WORK/classifier.parsi" > "$WORK/compile.log" 2>&1 || {
  echo "FAIL parsi could not compile the object:"
  tail -20 "$WORK/compile.log"
  exit 1
}

# The split, checked on the generated files rather than asserted in prose.
# Torch belongs to this object's translation unit; a page that REQUIREs it must
# inherit the linkage and not the header.
if grep -q "torch" "$HOME_DIR/ld/_DEMO::CLASSIFIER_.hpp" 2>/dev/null; then
  check "torch stays out of the object header" "present" "absent"
else
  check "torch stays out of the object header" "absent" "absent"
fi

if grep -q "torch" "$HOME_DIR/tmp/_DEMO::CLASSIFIER_.cpp" 2>/dev/null; then
  check "torch is in the object implementation" "present" "present"
else
  check "torch is in the object implementation" "absent" "present"
fi

# --- serve it --------------------------------------------------------------

LOG="$HOME_DIR/log/ai-e2e-server.log"
mkdir -p "$HOME_DIR/log" "$HOME_DIR/data"

echo "starting ziguratip (log: $LOG)"
"$HOME_DIR/bin/ziguratip" > "$LOG" 2>&1 &
SERVER_PID=$!

stop_server() {
  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
}
trap 'stop_server; rm -rf "$WORK"' EXIT

# WAIT FOR ZEYTUN, NOT FOR "ready". The log says "Zigurat is ready" while the
# HTTP listener is still coming up, so a plain grep for the word wins the race
# and the page is fetched from a port nobody is on yet -- which reads as an
# empty body and four failed assertions about the model.
i=0
while [ $i -lt 600 ]; do
  grep -q "Zeytun is ready" "$LOG" 2>/dev/null && break
  i=$((i + 1))
  sleep 0.1
done
grep -q "Zeytun is ready" "$LOG" 2>/dev/null || {
  echo "FAIL the server never finished starting; last of $LOG:"
  tail -5 "$LOG"
  exit 1
}

BODY=$(curl -s --max-time 60 "http://127.0.0.1:2190/predict.zt" || true)
echo "page said: $BODY"

field() { echo "$BODY" | tr ' ' '\n' | sed -n "s/^$1=//p"; }

INPUTS=$(field inputs)
S0=$(field seed0)
S137=$(field seed137)
A0=$(field again0)

check    "the page answered"                "$(test -n "$BODY" && echo yes || echo no)" "yes"
check    "the model reports its input width" "$INPUTS" "784"
check    "the same seed twice agrees"        "$A0"     "$S0"

# THE ONE THAT CATCHES A DEAD MODEL. Everything above passes if predict()
# returns a constant -- a from_blob that reads nothing, a forward that ignores
# its input, a page that never reaches the object at all.
check_ne "two seeds give two answers"        "$S0"     "$S137"

case "$S0" in
  ''|*[!0-9]*) check "the class is a number in range" "$S0" "0..9" ;;
  *) if [ "$S0" -ge 0 ] && [ "$S0" -le 9 ]; then
       check "the class is a number in range" "in" "in"
     else
       check "the class is a number in range" "$S0" "0..9"
     fi ;;
esac

echo
echo "cases    : $((pass + fail)) run, $fail failed"
if [ "$fail" -eq 0 ]; then
  echo "result   : PASS"
  exit 0
else
  echo "result   : FAIL"
  exit 1
fi
