#!/bin/sh
# Build the neural-network object from Cicili's emitted fragment, serve it, and
# ask it for predictions over HTTP.
#
#   Test/run-ai-e2e.sh                 against the torch stub -- always runs
#   LIBTORCH=/opt/torch/torch \
#     Test/run-ai-e2e.sh               against the real libtorch
#   CICILI_ROOT=../cicili \
#     Test/run-ai-e2e.sh               also re-emit the fragment and diff it
#
# LIBTORCH IS SPELLED THE WAY CICILI SPELLS IT, and $TORCH_ROOT is still
# accepted because this script used to be the only thing that read it.
#
# TIER B IS OPT-IN. One of those two variables selects it and nothing else
# does. An installed libtorch is NOT taken as permission to use it: tier B
# compiles against the real headers, which is minutes rather than seconds, and
# a suite that silently gets slower because of something else installed on the
# machine is a suite people stop running. If the pip package is around, tier A
# says so and prints the line that would switch -- offered, not taken.
#
# WHAT IT COVERS. The whole path in one go: C++ generated by Cicili from a
# (network …) description, spliced into a Parsi CLASS through BEGIN HPP and
# BEGIN CPP, compiled standalone into home/ld/lib_DEMO::CLASSIFIER_.so, loaded
# by the server, and reached by a page over HTTP. Nothing else in either
# repository's suite touches more than a piece of that.
#
# WHAT IT DOES NOT COVER. Whether the model is any good. The stub's Linear is
# not trained and neither is the real one here -- net_load is given an empty
# path on purpose. No assertion below reads an accuracy, and none should be
# added: this is a test of the plumbing, and a plumbing test that starts
# claiming things about a model is how a suite stops being trusted.

set -e

HERE=$(cd "$(dirname "$0")" && pwd)
TRUNK=$(cd "$HERE/.." && pwd)
HOME_DIR="$TRUNK/home"
AI="$HERE/ai"

pass=0
fail=0

check() {
  # check NAME ACTUAL EXPECTED -- an empty ACTUAL is never a pass, for the same
  # reason as check_ne: nothing compares equal to nothing a little too easily.
  if [ -z "$2" ]; then
    echo "FAIL $1: got nothing, want '$3'"
    fail=$((fail + 1))
  elif [ "$2" = "$3" ]; then
    echo "ok   $1"
    pass=$((pass + 1))
  else
    echo "FAIL $1: got '$2' want '$3'"
    fail=$((fail + 1))
  fi
}

check_ne() {
  # check_ne NAME A B  -- the two must DIFFER, and neither may be empty.
  #
  # THE EMPTY CASE IS THE ONE THAT MATTERS. When the page answers nothing --
  # a server not up yet, an object that would not load -- every field parses
  # as the empty string, and "" differs from nothing and equals everything.
  # Without this guard a total failure to reach the model reads as agreement.
  if [ -z "$2" ] || [ -z "$3" ]; then
    echo "FAIL $1: one side was empty, so there was nothing to compare"
    fail=$((fail + 1))
  elif [ "$2" != "$3" ]; then
    echo "ok   $1"
    pass=$((pass + 1))
  else
    echo "FAIL $1: both were '$2', expected them to differ"
    fail=$((fail + 1))
  fi
}

if [ ! -x "$HOME_DIR/bin/ziguratip" ]; then
  echo "build first: make -C $TRUNK" >&2
  exit 1
fi

# --- the fragment ----------------------------------------------------------
#
# Test/ai/classifier.{hpp,cpp} are committed, so this runs with no Cicili
# checkout at all. With one, they are re-emitted and diffed -- which is what
# catches the generator drifting away from the copy committed here. A drift is
# a failure, not a silent overwrite: the point is to be told.

if [ -n "$CICILI_ROOT" ]; then
  CICILI_ROOT=$(cd "$CICILI_ROOT" && pwd)
  echo "re-emitting the fragment from $CICILI_ROOT"
  ( cd "$CICILI_ROOT" && sbcl --script cicili.lisp ./example/mnist-fragment.cicili >/tmp/ai-emit.log 2>&1 ) \
    || { echo "FAIL cicili could not emit the fragment; see /tmp/ai-emit.log"; exit 1; }
  for f in classifier.hpp classifier.cpp; do
    if diff -q "$CICILI_ROOT/example/$f" "$AI/$f" >/dev/null 2>&1; then
      check "$f matches what cicili emits" "same" "same"
    else
      check "$f matches what cicili emits" "differs" "same"
      diff -u "$AI/$f" "$CICILI_ROOT/example/$f" | head -30
    fi
  done
else
  echo "note: CICILI_ROOT unset, using the committed fragment as-is"
fi

# --- the torch header ------------------------------------------------------

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# STAGE INTO home/tmp, NOT JUST home/ld, and clear what was there first.
#
# The generated _DEMO::CLASSIFIER_.cpp is written into home/tmp and compiled
# there, and `#include "torch_stub.hpp"' is a quoted include -- so the
# compiler looks in home/tmp before it looks anywhere on -I. A stale copy left
# in home/tmp from an earlier run is therefore the one that gets compiled, and
# nothing says so: the build succeeds, the page answers, and every assertion
# passes against a header nobody edited.
#
# This is not hypothetical. It is what happened while this script was being
# written -- a deliberately broken stub was staged, the suite went green, and
# the reason was a copy in home/tmp from an earlier compile. Clearing both
# directories is what makes an edit to Test/ai/ actually reach the object.
rm -f "$HOME_DIR/tmp/torch_stub.hpp" "$HOME_DIR/tmp/classifier.hpp" "$HOME_DIR/tmp/classifier.cpp" \
      "$HOME_DIR/ld/torch_stub.hpp"  "$HOME_DIR/ld/classifier.hpp"  "$HOME_DIR/ld/classifier.cpp" \
      "$HOME_DIR/ld/lib_DEMO::CLASSIFIER_.so" "$HOME_DIR/obj/_DEMO::CLASSIFIER_.o" \
      "$HOME_DIR/ld/lib_PREDICT_.so"          "$HOME_DIR/obj/_PREDICT_.o"

cp "$AI/classifier.hpp" "$AI/classifier.cpp" "$HOME_DIR/ld/"
cp "$AI/classifier.hpp" "$AI/classifier.cpp" "$HOME_DIR/tmp/"

# $LIBTORCH, or $TORCH_ROOT under its old name. Nothing is discovered here:
# whether to spend tier B's compile time is the caller's decision.
if [ -z "$LIBTORCH" ] && [ -n "$TORCH_ROOT" ]; then
  LIBTORCH="$TORCH_ROOT"
fi

if [ -n "$LIBTORCH" ]; then
  if [ ! -f "$LIBTORCH/include/torch/torch.h" ] && [ ! -f "$LIBTORCH/include/torch/csrc/api/include/torch/torch.h" ]; then
    echo "FAIL libtorch at $LIBTORCH has no include/torch/torch.h" >&2
    echo "     set \$LIBTORCH to the directory holding include/ and lib/" >&2
    exit 1
  fi
  echo "tier B: against the real libtorch at $LIBTORCH"

  # THE OBJECT CARRIES ITS OWN FLAGS. COMPILE reaches the C++ compile of this
  # object and LINK reaches its link, both scoped to the object
  # (Compiler/compilerddl.cpp, ClauseScope), so neither is added to the
  # server's home/etc/ziguratip.conf and taken out again.
  #
  # That is what this used to do, and it was the worst thing in the script: a
  # global config file edited in place, restored by a trap, and wrong for every
  # other object compiled while the run was in flight. -I in particular HAD to
  # go that way -- parsi builds its compile line from COMPILER/CPP_FLAGS and
  # reads no environment variable, so an exported CPPFLAGS was silently
  # ignored, and it failed as a missing <torch/torch.h> that looked like a
  # broken $LIBTORCH.
  #
  # -std=c++17 rather than the c++11 the config ships: libtorch 2.x does not
  # compile under c++11 at all. The object's flags are appended after the
  # configured ones and the last -std on the line wins.
  sed -e 's|#include "torch_stub.hpp"|#include <torch/torch.h>|' \
      -e "s|INCLUDE '<memory>';|INCLUDE '<memory>';\n\tCOMPILE '-std=c++17';\n\tCOMPILE '-I$LIBTORCH/include';\n\tCOMPILE '-I$LIBTORCH/include/torch/csrc/api/include';\n\tLINK '-L$LIBTORCH/lib';\n\tLINK '-Wl,-rpath,$LIBTORCH/lib';\n\tLINK '-ltorch';\n\tLINK '-ltorch_cpu';\n\tLINK '-lc10';|" \
      "$AI/classifier.parsi" > "$WORK/classifier.parsi"

  grep -q "COMPILE '-std=c++17';" "$WORK/classifier.parsi" || {
    echo "FAIL could not add COMPILE to classifier.parsi -- has the INCLUDE line changed?"
    grep -n "INCLUDE" "$AI/classifier.parsi"
    exit 1
  }

  # The object dlopens libtorch at request time, so the SERVER needs the
  # library path too, not just the compiler.
  LD_LIBRARY_PATH="$LIBTORCH/lib:$LD_LIBRARY_PATH"
  export LD_LIBRARY_PATH

  # TRAINED WEIGHTS, if they are here. Test/ai/classifier.pt is what cicili's
  # example/mnist-train.cpp writes after eight epochs on the real MNIST --
  # 98.17% on the held-out set. Without it the network is untrained, which is
  # still a valid run: everything except the digit check means the same.
  if [ -f "$AI/classifier.pt" ]; then
    CLASSIFIER_WEIGHTS="$AI/classifier.pt"
    export CLASSIFIER_WEIGHTS
    echo "weights: $CLASSIFIER_WEIGHTS"
  else
    echo "note: no Test/ai/classifier.pt, the network will be untrained"
  fi

  # And the test set, for classifying real digits. Not committed -- it is 7.8 MB
  # of someone else's data -- so this looks where the README says to put it.
  if [ -z "$MNIST_DIR" ] && [ -f "$AI/t10k-images-idx3-ubyte" ]; then
    MNIST_DIR="$AI"
  fi
  [ -n "$MNIST_DIR" ] && export MNIST_DIR
else
  # $LIBTORCH ESCAPED, so the name is printed rather than the empty value it
  # necessarily has on this branch.
  echo "tier A: against Test/ai/torch_stub.hpp (set \$LIBTORCH for the real library)"

  # The one place python3 is asked, and only to make the offer concrete. It
  # selects nothing -- see the header. Silent if there is no python3, no torch,
  # or nothing that looks like a distribution.
  found=$(python3 -c "import torch,os;print(os.path.dirname(torch.__file__))" 2>/dev/null || true)
  if [ -n "$found" ] && [ -d "$found/include" ]; then
    echo "        libtorch looks installed -- LIBTORCH=$found $0"
  fi

  cp "$AI/torch_stub.hpp" "$HOME_DIR/ld/"
  cp "$AI/torch_stub.hpp" "$HOME_DIR/tmp/"
  cp "$AI/classifier.parsi" "$WORK/classifier.parsi"
fi

export ZIGURATIP_HOME="$HOME_DIR"
export DYLD_LIBRARY_PATH="$HOME_DIR/lib:$DYLD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$HOME_DIR/lib:$LD_LIBRARY_PATH"

echo "compiling the object"
"$HOME_DIR/bin/parsi" "$WORK/classifier.parsi" > "$WORK/compile.log" 2>&1 || {
  echo "FAIL parsi could not compile the object:"
  tail -20 "$WORK/compile.log"
  exit 1
}

# The split, checked on the generated files rather than asserted in prose.
# Torch belongs to this object's translation unit; a page that REQUIREs it must
# inherit the linkage and not the header.
if grep -q "torch" "$HOME_DIR/ld/_DEMO::CLASSIFIER_.hpp" 2>/dev/null; then
  check "torch stays out of the object header" "present" "absent"
else
  check "torch stays out of the object header" "absent" "absent"
fi

if grep -q "torch" "$HOME_DIR/tmp/_DEMO::CLASSIFIER_.cpp" 2>/dev/null; then
  check "torch is in the object implementation" "present" "present"
else
  check "torch is in the object implementation" "absent" "present"
fi

# --- serve it --------------------------------------------------------------

LOG="$HOME_DIR/log/ai-e2e-server.log"
mkdir -p "$HOME_DIR/log" "$HOME_DIR/data"

echo "starting ziguratip (log: $LOG)"
"$HOME_DIR/bin/ziguratip" > "$LOG" 2>&1 &
SERVER_PID=$!

stop_server() {
  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
}
# NOTHING TO RESTORE ANY MORE. This trap used to put home/etc/ziguratip.conf
# back, because tier B patched the server's global CPP_FLAGS to reach libtorch;
# forgetting it left -std=c++17 and a torch include path in the config for every
# later build in the tree. The object now carries those flags in its own COMPILE
# clauses, so the config is never written and there is nothing to undo.
trap 'stop_server; rm -rf "$WORK"' EXIT

# WAIT FOR ZEYTUN, NOT FOR "ready". The log says "Zigurat is ready" while the
# HTTP listener is still coming up, so a plain grep for the word wins the race
# and the page is fetched from a port nobody is on yet -- which reads as an
# empty body and four failed assertions about the model.
i=0
while [ $i -lt 600 ]; do
  grep -q "Zeytun is ready" "$LOG" 2>/dev/null && break
  i=$((i + 1))
  sleep 0.1
done
grep -q "Zeytun is ready" "$LOG" 2>/dev/null || {
  echo "FAIL the server never finished starting; last of $LOG:"
  tail -5 "$LOG"
  exit 1
}

# TWICE, because one request cannot show that anything survived it. The page is
# constructed per request, so a model held as a page member would be loaded
# again here -- and `loads' would climb.
BODY=$(curl -s --max-time 60 "http://127.0.0.1:2190/predict.zt" || true)
echo "page said: $BODY"

SECOND=$(curl -s --max-time 60 "http://127.0.0.1:2190/predict.zt" || true)
echo "and again : $SECOND"

field() { echo "$BODY" | tr ' ' '\n' | sed -n "s/^$1=//p"; }

INPUTS=$(field inputs)
S0=$(field seed0)
S137=$(field seed137)
A0=$(field again0)
P0=$(field score0)
P137=$(field score137)
PA0=$(field scoreagain0)

check    "the page answered"                "$(test -n "$BODY" && echo yes || echo no)" "yes"
check    "the second request answered"      "$(test -n "$SECOND" && echo yes || echo no)" "yes"

# THE POOL. The checkpoint is read once however many requests arrive; without
# ModelPool this is 1 then 2, because the page that owns the model is built
# fresh for each one.
LOADS=$(field loads)
LOADS2=$(echo "$SECOND" | tr ' ' '\n' | sed -n "s/^loads=//p")
check    "the checkpoint was read once"     "$LOADS"  "1"
check    "and not again on the next request" "$LOADS2" "1"
check    "the model reports its input width" "$INPUTS" "784"
check    "the same seed twice agrees"        "$A0"     "$S0"

check    "the same seed twice scores the same" "$PA0"   "$P0"

# THE ONE THAT CATCHES A DEAD MODEL, and it asks for a SCORE rather than a
# class. Two seeds sharing a class proves nothing: an untrained network's
# argmax is very nearly input-independent, one class wins for almost every
# picture, and asserting on it failed against real libtorch while passing
# against the stub -- a test that was wrong rather than a model that was.
#
# The largest log-probability moves with the input for a trained and an
# untrained network alike. Two pictures scoring the same to six decimal places
# did not both reach the model.
check_ne "two seeds give two scores"         "$P0"     "$P137"

# THE PAYOFF, when there is a trained model and a test set to read: ten real
# MNIST digits, the model's answer over the true label. Every pair must agree.
#
# Pairs rather than a fixed string, so retraining does not break the test --
# what is asserted is that the model is right, not that it is the same model.
# A 98%-accurate net getting all ten is not luck: these are the first ten test
# digits, and they are not hard ones.
DIGITS=$(field digits)
if [ -z "$DIGITS" ] || [ "${DIGITS%%,*}" = "-1/-1" ]; then
  echo "skip real digits: no MNIST_DIR with t10k-images-idx3-ubyte (see Test/ai/README.md)"
else
  bad=0; seen=0
  for pair in $(echo "$DIGITS" | tr ',' ' '); do
    got=${pair%%/*}; want=${pair##*/}
    seen=$((seen + 1))
    [ "$got" = "$want" ] || { bad=$((bad + 1)); echo "  digit $seen: model said $got, truth $want"; }
  done
  check "ten real MNIST digits were read"   "$seen" "10"
  check "the trained model got them right"  "$bad"  "0"
fi

case "$S0" in
  ''|*[!0-9]*) check "the class is a number in range" "$S0" "0..9" ;;
  *) if [ "$S0" -ge 0 ] && [ "$S0" -le 9 ]; then
       check "the class is a number in range" "in" "in"
     else
       check "the class is a number in range" "$S0" "0..9"
     fi ;;
esac

echo
echo "cases    : $((pass + fail)) run, $fail failed"
if [ "$fail" -eq 0 ]; then
  echo "result   : PASS"
  exit 0
else
  echo "result   : FAIL"
  exit 1
fi
