
PROJECT := StreamIO
TYPE := Library

HEADERS := binarystream.h \
	hbostream.h \
	nbostream.h \
	bufferstream.h \
	filestream.h \
	textstream.h \
	arraybuf.h \
	arraystream.h

SOURCES := binarystream.cpp \
	hbostream.cpp \
	nbostream.cpp \
	bufferstream.cpp \
	filestream.cpp \
	arraybuf.cpp \
	arraystream.cpp

LIBS :=

include ../Makefile.global
