
PROJECT := HTTP
TYPE := Library

HEADERS := session.h \
	httpexception.h \
	httprequest.h \
	httpresponse.h \
	httpserver.h \
	basepage.h \
	http.h

SOURCES := session.cpp \
	httpexception.cpp \
	httprequest.cpp \
	httpresponse.cpp \
	httpserver.cpp \
	basepage.cpp

LIBS := -lType -lStreamIO -lCore -lCryptography -lLibrary -lSocketIO

include ../Makefile.global

