
PROJECT := HTTP
TYPE := Library

HEADERS := session.hpp \
	httpexception.hpp \
	httprequest.hpp \
	httpresponse.hpp \
	httpserver.hpp \
	basepage.hpp \
	http.hpp

SOURCES := session.cpp \
	httpexception.cpp \
	httprequest.cpp \
	httpresponse.cpp \
	httpserver.cpp \
	basepage.cpp

LIBS := -lType -lStreamIO -lCore -lCryptography -lLibrary -lSocketIO

include ../Makefile.global

