
PROJECT := Core
TYPE := Library

HEADERS := zexception.hpp \
	utility.hpp \
	array.hpp \
	polynomial.hpp \
	bigint.hpp

SOURCES := zexception.cpp \
	utility.cpp \
	array.cpp \
	polynomial.cpp \
	bigint.cpp

LIBS :=

include ../Makefile.global
