
PROJECT := Type
TYPE := Library

HEADERS := tdbyte.hpp \
	typeobject.hpp \
	typebool.hpp \
	typechar.hpp \
	typebyte.hpp \
	typeubyte.hpp \
	typeshort.hpp \
	typeushort.hpp \
	typeint.hpp \
	typeuint.hpp \
	typelong.hpp \
	typeulong.hpp \
	typefloat.hpp \
	typedouble.hpp \
	typereal.hpp \
	typetimestamp.hpp \
	typestring.hpp \
	typetext.hpp \
	typevector.hpp \
	types.hpp

SOURCES := tdbyte.cpp \
	typeobject.cpp \
	typebool.cpp \
	typechar.cpp \
	typebyte.cpp \
	typeubyte.cpp \
	typeshort.cpp \
	typeushort.cpp \
	typeint.cpp \
	typeuint.cpp \
	typelong.cpp \
	typeulong.cpp \
	typefloat.cpp \
	typedouble.cpp \
	typereal.cpp \
	typetimestamp.cpp \
	typestring.cpp \
	typetext.cpp \
	types.cpp

LIBS := -lCore -lStreamIO

include ../Makefile.global
