
PROJECT := Core
TYPE := Library

HEADERS := zexception.h \
	utility.h \
	array.h \
	polynomial.h \
	bigint.h

SOURCES := zexception.cpp \
	utility.cpp \
	array.cpp \
	polynomial.cpp \
	bigint.cpp

LIBS :=

include ../Makefile.global
