
PROJECT := StreamIO
TYPE := Library

HEADERS := binarystream.hpp \
	hbostream.hpp \
	nbostream.hpp \
	bufferstream.hpp \
	networkstream.hpp \
	filestream.hpp \
	textstream.hpp \
	arraybuf.hpp \
	arraystream.hpp

SOURCES := binarystream.cpp \
	hbostream.cpp \
	nbostream.cpp \
	bufferstream.cpp \
	networkstream.cpp \
	filestream.cpp \
	arraybuf.cpp \
	arraystream.cpp

LIBS :=

include ../Makefile.global
