
PROJECT := Compiler
TYPE := Library

HEADERS := tokenizeexception.hpp \
	tokentype.hpp \
	token.hpp \
	tokenizer.hpp \
	expression.hpp \
	parseexception.hpp \
	parser.hpp \
	compileexception.hpp \
	headcompiler.hpp \
	exprcompiler.hpp \
	wherecompiler.hpp \
	compiler.hpp

SOURCES := tokenizeexception.cpp \
	tokenizer.cpp \
	expression.cpp \
	parseexception.cpp \
	parser.cpp \
	compileexception.cpp \
	headcompiler.cpp \
	exprcompiler.cpp \
	wherecompiler.cpp \
	compiler.cpp \
	compilerddl.cpp \
	compilerdml.cpp

LIBS := -lCore -lConfiguration -lCryptography -lLibrary 

include ../Makefile.global
