
PROJECT := Compiler
TYPE := Library

HEADERS := tokenizeexception.h \
	tokentype.h \
	token.h \
	tokenizer.h \
	expression.h \
	parseexception.h \
	parser.h \
	compileexception.h \
	headcompiler.h \
	exprcompiler.h \
	wherecompiler.h \
	compiler.h

SOURCES := tokenizeexception.cpp \
	tokenizer.cpp \
	expression.cpp \
	parseexception.cpp \
	parser.cpp \
	compileexception.cpp \
	headcompiler.cpp \
	exprcompiler.cpp \
	wherecompiler.cpp \
	compiler.cpp \
	compilerddl.cpp \
	compilerdml.cpp

LIBS := -lCore -lConfiguration -lCryptography -lLibrary 

include ../Makefile.global
