
PROJECT := MVCCS
TYPE := Library

HEADERS := memorybase.h \
	rowstate.h \
	rowlock.h \
	isolationlevel.h \
	control.h \
	pointer.h \
	transaction.h \
	memoryexception.h \
	memory.h \
	basetable.h \
	indexexception.h \
	btreerecord.h \
	btreenode.h \
	btreekey.h \
	btreevalue.h \
	btreeindex.h \
	sequenceexception.h \
	basesequence.h \
	globals.h

SOURCES := pointer.cpp \
	transaction.cpp \
	btreerecord.cpp \
	btreenode.cpp \
	basetable.cpp \
	memory.cpp \
	globals.cpp

LIBS := -lCore -lCryptography -lStreamIO

include ../Makefile.global
