
PROJECT := Encoding
TYPE := Library

HEADERS := base16.h \
	base32.h \
	base32hex.h \
	base64.h \
	base64url.h \
	cte.h \
	der.h \
	asn1.h

SOURCES := base16.cpp \
	base32.cpp \
	base32hex.cpp \
	base64.cpp \
	base64url.cpp \
	cte.cpp \
	der.cpp \
	asn1.cpp

include ../Makefile.global

