
COUNTRY: US
ORGANIZATION:
ORGANIZATIONAL_UNIT:
DISTINGUISHED_NAME_QUALIFIER: The Zigurat Informational Platform Project
STATE_OR_PROVINCE_NAME: Chicago
COMMON_NAME: ZiguratIP
SERIAL_NUMBER: 
LOCALITY: 
TITLE: 
NAME: 
SURNAME: 
GIVEN_NAME: 
INITIALS: 
PSEUDONYM: 
GENERATION_QUALIFIER: 
DOMAIN_COMPONENT: ziguratip.com
EMAIL_ADDRESS: info@ziguratip.com
