
PROJECT := MVCCS
TYPE := Library

HEADERS := memorybase.hpp \
	rowstate.hpp \
	rowlock.hpp \
	isolationlevel.hpp \
	control.hpp \
	pointer.hpp \
	transaction.hpp \
	memoryexception.hpp \
	memory.hpp \
	basetable.hpp \
	indexexception.hpp \
	btreerecord.hpp \
	btreenode.hpp \
	btreekey.hpp \
	btreevalue.hpp \
	btreeindex.hpp \
	sequenceexception.hpp \
	basesequence.hpp \
	globals.hpp

SOURCES := pointer.cpp \
	transaction.cpp \
	btreerecord.cpp \
	btreenode.cpp \
	basetable.cpp \
	memory.cpp \
	globals.cpp

LIBS := -lCore -lCryptography -lStreamIO

include ../Makefile.global
