
PROJECT := Type
TYPE := Library

HEADERS := tdbyte.h \
	typeobject.h \
	typebool.h \
	typechar.h \
	typebyte.h \
	typeubyte.h \
	typeshort.h \
	typeushort.h \
	typeint.h \
	typeuint.h \
	typelong.h \
	typeulong.h \
	typefloat.h \
	typedouble.h \
	typereal.h \
	typetimestamp.h \
	typestring.h \
	typetext.h \
	typevector.h \
	types.h

SOURCES := tdbyte.cpp \
	typeobject.cpp \
	typebool.cpp \
	typechar.cpp \
	typebyte.cpp \
	typeubyte.cpp \
	typeshort.cpp \
	typeushort.cpp \
	typeint.cpp \
	typeuint.cpp \
	typelong.cpp \
	typeulong.cpp \
	typefloat.cpp \
	typedouble.cpp \
	typereal.cpp \
	typetimestamp.cpp \
	typestring.cpp \
	typetext.cpp \
	types.cpp

LIBS := -lCore -lStreamIO

include ../Makefile.global
