
PROJECT := Cryptography
TYPE := Library

HEADERS := sha-private.hpp \
	sha.hpp \
	shahelper.hpp \
	aes.hpp \
	rsa.hpp \
	certificateexception.hpp \
	x509.hpp

SOURCES := sha1.cpp \
	sha224-256.cpp \
	sha384-512.cpp \
	usha.cpp \
	hmac.cpp \
	hkdf.cpp \
	shahelper.cpp \
	aes.cpp \
	rsa.cpp \
	x509.cpp

include ../Makefile.global

