
PROJECT := Encoding
TYPE := Library

HEADERS := base16.hpp \
	base32.hpp \
	base32hex.hpp \
	base64.hpp \
	base64url.hpp \
	cte.hpp \
	der.hpp \
	asn1.hpp

SOURCES := base16.cpp \
	base32.cpp \
	base32hex.cpp \
	base64.cpp \
	base64url.cpp \
	cte.cpp \
	der.cpp \
	asn1.cpp

include ../Makefile.global

