
LOCALE: en_US.utf8 # locale -a
#HOME_PATH: Install Directory Path
#CATALOG_PATH: Install Directory Path/catalog

RESET_MODE: TRUE # it's going to erase all data
TRACE_MODE: TRUE

LIBRARY:
	GLOBAL_CACHE_MODE: FALSE # global for process
	LOCAL_CACHE_MODE: TRUE # local for thread

TRANSACTION:
	MODE: NON-AUTOCOMMIT # AUTOCOMMIT NON-AUTOCOMMIT
	ISOLATION_LEVEL: READ-COMMITTED # READ-UNCOMMITTED READ-COMMITTED REPEATABLE-READ SNAPSHOT SERIALIZABLE

#PARSER:
#	TRACE_MODE: FALSE
#	PATTERNS_FILE: Install Directory Path/etc/patterns.conf

COMPILER:
	CPP:          g++
	CPP_FLAGS:    -Wall -std=c++11 -fPIC -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
	LD_FLAGS:     -shared -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
#	INCLUDE_PATH: Install Directory Path/include
#	OBJ_PATH:     Install Directory Path/obj
#	LIB_PATH:     Install Directory Path/lib
#	TMP_PATH:     Install Directory Path/tmp
#	LD_PATH:      Install Directory Path/ld
	TRACE_MODE:   FALSE

MEMORY:
	BLOCK_SIZE: 8192

#SERVER:
#	TYPE: IPC
#	PATH: /tmp/ZiguratIP
#	BACKLOG: 5

SERVER:
	TYPE: TCP
	PORT: 2160 # ZIGO
	BACKLOG: 5 # total transactions
	TIMEOUT: 60 # seconds

HTTP:
	PORT: 2190 # 80 2190 zigo
	BACKLOG: 5 # total synchronous connections
	TIMEOUT: 60 # seconds
	BLOCKING_MODE: TRUE # keep-alive
	ASYNCHRONOUS_MODE: FALSE # pipelining
	MAX_URL_LENGTH: 8000
	MAX_HEADERS_LENGTH: 16000
	MAX_CONTENT_LENGTH: 2000000000
#	MIME_FILE: Install Directory Path/etc/mime.conf
