
LOCALE: en_US.utf8 # locale -a
HOME_PATH: /home/saman/Projects/Zigurat/home
CATALOG_PATH: /home/saman/Projects/Zigurat/home/catalog

RESET_MODE: FALSE
TRACE_MODE: TRUE

TRANSACTION:
	MODE: NON-AUTOCOMMIT # AUTOCOMMIT NON-AUTOCOMMIT
	ISOLATION_LEVEL: READ-COMMITTED # READ-UNCOMMITTED READ-COMMITTED REPEATABLE-READ SNAPSHOT SERIALIZABLE

PARSER:
	TRACE_MODE: FALSE
	PATTERNS_FILE: /home/saman/Projects/Zigurat/home/etc/patterns.conf

COMPILER:
	CPP:          c++
	CPP_FLAGS:    -Wall -std=c++17 -fPIC -O3
	LD_FLAGS:     -shared
	INCLUDE_PATH: /home/saman/Projects/Zigurat/home/include
	OBJ_PATH:     /home/saman/Projects/Zigurat/home/obj
	LIB_PATH:     /home/saman/Projects/Zigurat/home/lib
	TMP_PATH:     /home/saman/Projects/Zigurat/home/tmp
	LD_PATH:      /home/saman/Projects/Zigurat/home/ld

MEMORY:
	BLOCK_SIZE: 8192
	TRACE_MODE: TRUE

#SERVER:
#	TYPE: IPC
#	PATH: /tmp/zigurat
#	BACKLOG: 5

SERVER:
	TYPE: TCP
	PORT: 2160 # ZIGO
	BACKLOG: 5
