
PROJECT := Connector
TYPE := Library

HEADERS := connector.hpp \
	connectorexception.hpp \
	resulttype.hpp \
	rpcpool.hpp

SOURCES := connector.cpp \
	rpcpool.cpp

LIBS := -lCore -lConfiguration -lStreamIO -lSocketIO

include ../Makefile.global

