
PROJECT := Connector
TYPE := Library

HEADERS := connector.h \
	connectorexception.h \
	resulttype.h

SOURCES := connector.cpp

LIBS := -lCore -lConfiguration -lStreamIO -lSocketIO

include ../Makefile.global

