
PROJECT := Configuration
TYPE := Library

HEADERS := option.h \
	configurationexception.h \
	configuration.h \
	argumentexception.h \
	argument.h

SOURCES := option.cpp \
	configurationexception.cpp \
	configuration.cpp \
	argument.cpp

LIBS := -lCore

include ../Makefile.global

