
PROJECT := Configuration
TYPE := Library

HEADERS := option.hpp \
	configurationexception.hpp \
	configuration.hpp \
	argumentexception.hpp \
	argument.hpp

SOURCES := option.cpp \
	configurationexception.cpp \
	configuration.cpp \
	argument.cpp

LIBS := -lCore

include ../Makefile.global

